---
- name: Install CrewAI and CrewAI tools
  ansible.builtin.shell: "source {{ conda_sh_directory }} && conda activate {{ conda_env_directory }} && pip install --no-input crewai==0.95.0 && pip install --no-input crewai-tools==0.25.8"
  register: shell_output_crewai_install
  retries: 3
  delay: 10
  until: shell_output_crewai_install.rc == 0
  tags:
    - sre_agent

- name: Clone Agent Analytics SDK
  ansible.builtin.shell: "source {{ conda_sh_directory }} && conda activate {{ conda_env_directory }} && git clone https://{{ agent_analytics_sdk_username}}:{{ agent_analytics_sdk_token }}@github.ibm.com/Rohan-Arora/agent-analytics-sdk.git --branch v0.2.3 /runner/agent-analytics-sdk"
  register: shell_output_analytics_sdk
  retries: 3
  delay: 10
  until: shell_output_analytics_sdk.rc == 0
  tags:
   - sre_agent
  when: agent_analytics_sdk_username is defined and agent_analytics_sdk_token is defined

- name: Run CrewAI install
  ansible.builtin.shell: "source {{ conda_sh_directory }} && conda activate {{ conda_env_directory }} && cd {{ sre_agent_directory }} && crewai install"
  register: shell_output_crewai_install_env
  retries: 3
  delay: 10
  until: shell_output_crewai_install_env.rc == 0
  tags:
   - sre_agent
